AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  keyhole-finder

  Sample SAM Template for keyhole-finder
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SubscriptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: KeyholeSubscriptions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: date
          AttributeType: S
        - AttributeName: subscriber
          AttributeType: S
      KeySchema:
        - AttributeName: date
          KeyType: HASH
        - AttributeName: subscriber
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: subscriber-index
          KeySchema:
            - AttributeName: subscriber
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY

  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: sms-listener-lambda-function-role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: subscriptions-table-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: !GetAtt SubscriptionsTable.Arn
              - Effect: Allow
                Action: mobiletargeting:SendMessages
                Resource: "arn:aws:mobiletargeting:us-east-1:501159871365:apps/91d70cfa0fb946a3b0ca034a3f89149e/messages"

  SMSReceiptTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: KeyholeFinder
      TopicName: KeyholeFinderInbound

  HelloSmsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: sms-hello/
      Handler: app.receiveSMS
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:501159871365:SMSBotTest

  ReceiveSMSFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda-functions/
      Handler: listener.listen
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Role: !GetAtt
        - LambdaFunctionRole
        - Arn
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SMSReceiptTopic